spring.application.name=carcompass

# Database Setup
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/test}

# For Railway deployment, override with the full URI via env variable
# spring.data.mongodb.uri=${MONGO_URL}

# Mongock configuration
mongock.migration-scan-package=com.practice.carcompass.dbmigrations
